content:
  - name: "home"
    label: "Home Page"
    type: "collection"
    path: "src/content/index"
    format: "markdown"
    fields:
      - name: "title"
        label: "Título Principal"
        type: "string"
      - name: "description"
        label: "Descripción"
        type: "text"