media:
  - name: files
    label: Files
    input: files/documents
    output: /files/documents
    categories: [ document ]
  - label: images
    label: Images
    input: images
    output: /images
    extensions: [ png, webp ]
content:
  - name: "home"
    label: "Home Page"
    type: "collection"
    path: "src/content/home"
    filename: "index.md"
    format: "markdown"
    fields:
      - name: "title"
        label: "Título Principal"
        type: "string"
      - name: "description"
        label: "Descripción"
        type: "text"