collections:
  - name: "home"
    label: "Home Page"
    folder: "src/content/home"
    format: "markdown"
    fields:
      - name: "title"
        label: "Título Principal"
        widget: "string"
      - name: "description"
        label: "Descripción"
        widget: "text"
